name: bucket_list
packages:
  - bucket_list
scripts:
  codegen:
    run: >-
      dart run build_runner build --delete-conflicting-outputs &&
      fluttergen &&
      dart pub global run intl_utils:generate

  flutterfire:
    run: >-
      flutterfire configure 
      --project=bucketlist-2137-prod
      --account=mwyczarski@gmail.com
      --platforms=ios,android 
      -o "lib/firebase_options_prod.dart" 
      --yes 
      -f
      --android-package-name=pl.wsiiz.bucket_list
      --ios-bundle-id=pl.wsiiz.bucket_list
